// Copyright (c) Microsoft. All rights reserved.

using System;
using System.Collections.Generic;
using System.Net;
using Helpers;
using Helpers.Http;
using Helpers.Models.TelemetryAlarms;
using Helpers.Models.TelemetryRules;
using Newtonsoft.Json;
using Xunit;
using Xunit.Abstractions;

namespace Telemetry
{
    [Collection("Telemetry Tests")]
    public class AlarmsTest
    {
        private readonly IHttpClient httpClient;
        private ITestOutputHelper logger;

        private const string DEFAULT_CHILLERS_GROUP_ID = "default_Chillers";
        private string instantChillerRuleId;
        private string averageChillerRuleId;
        private const int ALARM_TRIGGER_WAIT_MSEC = 90000;

        private const string ALARMS_ENDPOINT_SUFFIX = "/alarms";
        private const string RULES_ENDPOINT_SUFFIX = "/rules";
        private const string ALARMSBYRULE_ENDPOINT_SUFFIX = "/alarmsbyrule";

        // list of rules to delete when tests are complete
        private List<string> disposeRulesList;

        public AlarmsTest(ITestOutputHelper logger)
        {
            this.httpClient = new HttpClient();
            this.logger = logger;
            this.disposeRulesList = new List<string>();
            this.instantChillerRuleId = "INSTANT_CHILLER_TEST_RULE";
            this.averageChillerRuleId = "AVERAGE_CHILLER_TEST_RULE";

            // Wait for seed data to run simulation before checking alarms
            Assert.True(SeedData.WaitForSeedComplete());

            // Create rules guaranteed to generate alarms with seed data.
            this.CreateRuleWithCalculation("Average", "60000", ref this.averageChillerRuleId);
            this.CreateRuleWithCalculation("Instant", "0", ref this.instantChillerRuleId);

            // Wait for alarms to be generated by faulty rules.
            System.Threading.Thread.Sleep(ALARM_TRIGGER_WAIT_MSEC);
        }

        /// <summary>
        /// Try to delete all created rules upon completion.
        /// Each test should add the id of any rules created
        /// to the disposeRuleslist.
        /// </summary>
        ~AlarmsTest()
        {
            this.logger.WriteLine("Alarms test cleanup: Deleting " + this.disposeRulesList.Count + " rules.");

            foreach (var ruleId in this.disposeRulesList)
            {
                var request = new HttpRequest(Constants.TELEMETRY_ADDRESS + "/rules/" + ruleId);

                var response = this.httpClient.DeleteAsync(request).Result;
                if (response.StatusCode != HttpStatusCode.OK)
                {
                    this.logger.WriteLine("Unable to delete test rule id:" + ruleId);
                }
            }
        }

        /// <summary>
        /// Integration test using a real HTTP instance.
        /// Test that the service starts normally and returns ok status
        /// </summary>
        [Fact, Trait(Constants.TEST, Constants.INTEGRATION_TEST)]
        public void GetListReturnsAlarms_ForAllDevicesInTheLastHour()
        {
            // Arrange 
            const string PARAMETERS = "?devices=chiller-01.0%2C" +
                                      "elevator-02.0%2Cchiller-02.0%2C" +
                                      "prototype-02.0%2Ctruck-02.0%2C" +
                                      "truck-01.0%2Cengine-01.0%2C" +
                                      "prototype-01.0%2Cengine-02.0%2C" +
                                      "elevator-01.0&from=NOW-PT1H&to=NOW";

            // Act
            var request = new HttpRequest(Constants.TELEMETRY_ADDRESS + ALARMS_ENDPOINT_SUFFIX + PARAMETERS);
            var response = this.httpClient.GetAsync(request).Result;
            var alarmListResponse = JsonConvert.DeserializeObject<AlarmListApiModel>(response.Content);

            // Assert
            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
            Assert.NotEmpty(alarmListResponse.Items);
        }

        [Fact, Trait(Constants.TEST, Constants.INTEGRATION_TEST)]
        public void GetByIdReturnsDetails_ForExistingAlarm()
        {
            // Arrange 
            const string PARAMETERS = "?devices=chiller-01.0%2Cchiller-02.0%2C";

            var listRequest = new HttpRequest(Constants.TELEMETRY_ADDRESS + ALARMS_ENDPOINT_SUFFIX + PARAMETERS);
            var listResponse = this.httpClient.GetAsync(listRequest).Result;
            var alarmList = JsonConvert.DeserializeObject<AlarmListApiModel>(listResponse.Content);
            var alarmId = alarmList.Items[0].Id;

            // Act
            var request = new HttpRequest(Constants.TELEMETRY_ADDRESS + ALARMS_ENDPOINT_SUFFIX + "/" + alarmId);
            var response = this.httpClient.GetAsync(request).Result;
            var alarm = JsonConvert.DeserializeObject<AlarmApiModel>(response.Content);

            // Assert
            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
            Assert.NotNull(alarm.ETag);
            Assert.NotNull(alarm.Id);
            Assert.NotNull(alarm.DeviceId);
            Assert.NotNull(alarm.Rule);
        }

        [Fact, Trait(Constants.TEST, Constants.INTEGRATION_TEST)]
        public void UpdateExistingAlarm_AcknowledgesAlarm()
        {
            // Arrange 
            const string ACKNOWLEDGED_STATUS = "acknowledged";
            const string PARAMETERS = "?devices=chiller-01.0%2Cchiller-02.0%2C";

            var listRequest = new HttpRequest(Constants.TELEMETRY_ADDRESS + ALARMS_ENDPOINT_SUFFIX + PARAMETERS);
            var listResponse = this.httpClient.GetAsync(listRequest).Result;
            var alarmList = JsonConvert.DeserializeObject<AlarmListApiModel>(listResponse.Content);
            var alarmRequest = alarmList.Items[0];

            alarmRequest.Status = ACKNOWLEDGED_STATUS;

            // Act
            var request = new HttpRequest(Constants.TELEMETRY_ADDRESS + ALARMS_ENDPOINT_SUFFIX + "/" + alarmRequest.Id);
            request.AddHeader("Content-Type", "application/json");
            request.SetContent(JsonConvert.SerializeObject(alarmRequest));

            var response = this.httpClient.GetAsync(request).Result;
            var updatedAlarm = JsonConvert.DeserializeObject<AlarmApiModel>(response.Content);

            // Assert
            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
            Assert.Equal(alarmRequest.Id, updatedAlarm.Id);
            Assert.Equal(ACKNOWLEDGED_STATUS, updatedAlarm.Status);
        }

        [Fact, Trait(Constants.TEST, Constants.INTEGRATION_TEST)]
        public void GetAlarmsByRuleListReturnsAlarmSummary()
        {
            // Arrange 
            var request = new HttpRequest(
                Constants.TELEMETRY_ADDRESS +
                ALARMSBYRULE_ENDPOINT_SUFFIX);

            // Act 

            var response = this.httpClient.GetAsync(request).Result;
            var alarmsByRuleResponse = JsonConvert.DeserializeObject<AlarmByRuleListApiModel>(response.Content);

            // Assert
            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
            Assert.NotEmpty(alarmsByRuleResponse.Items);
        }

        /// <summary>
        /// This test verifies that alarms are being generated for the instant rule created
        /// in the test constructor.
        /// </summary>
        [Fact, Trait(Constants.TEST, Constants.INTEGRATION_TEST)]
        public void GetAlarmsByRuleReturnsAlarms_ForInstantRuleCalculation()
        {
            // Arrange 
            var request = new HttpRequest(
                Constants.TELEMETRY_ADDRESS +
                ALARMSBYRULE_ENDPOINT_SUFFIX +
                "/" + this.instantChillerRuleId);

            // Act 
            var response = this.httpClient.GetAsync(request).Result;
            var alarmsByRuleResponse = JsonConvert.DeserializeObject<AlarmByRuleListApiModel>(response.Content);

            // Assert
            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
            Assert.NotEmpty(alarmsByRuleResponse.Items);
        }

        /// <summary>
        /// This test verifies that alarms are being generated for the average rule created
        /// in the test constructor.
        /// </summary>
        [Fact, Trait(Constants.TEST, Constants.INTEGRATION_TEST)]
        public void GetAlarmsByRuleReturnsAlarms_ForAverageRuleCalculation()
        {
            // Arrange 
            var request = new HttpRequest(
                Constants.TELEMETRY_ADDRESS +
                ALARMSBYRULE_ENDPOINT_SUFFIX +
                "/" + this.averageChillerRuleId);

            // Act
            var response = this.httpClient.GetAsync(request).Result;
            var alarmsByRuleResponse = JsonConvert.DeserializeObject<AlarmByRuleListApiModel>(response.Content);

            // Assert
            Assert.Equal(HttpStatusCode.OK, response.StatusCode);
            Assert.NotEmpty(alarmsByRuleResponse.Items);
        }

        private void CreateRuleWithCalculation(string calculation, string timePeriod, ref string id)
        {
            var condition = new ConditionApiModel()
            {
                Field = "temperature",
                Operator = "GreaterThan",
                Value = "1"
            };

            var conditions = new List<ConditionApiModel> { condition };

            var newRule = new RuleApiModel()
            {
                Id = id,
                Name = calculation + " Faulty Test Rule " + DateTime.Now.ToString("yyyyMMddHHmmss"),
                Description = "Test Description",
                GroupId = DEFAULT_CHILLERS_GROUP_ID,
                Severity = "Info",
                Enabled = true,
                Calculation = calculation,
                TimePeriod = timePeriod,
                Conditions = conditions
            };

            var request = new HttpRequest(Constants.TELEMETRY_ADDRESS + RULES_ENDPOINT_SUFFIX);
            request.AddHeader("Content-Type", "application/json");
            request.SetContent(JsonConvert.SerializeObject(newRule));

            var response = this.httpClient.PostAsync(request).Result;
            var ruleResponse = JsonConvert.DeserializeObject<RuleApiModel>(response.Content);

            // Update the saved rule ID
            id = ruleResponse.Id;

            this.disposeRulesList.Add(ruleResponse.Id); // Dispose after tests run
        }
    }
}
